### ISSUE TITLE
Empty content for GetStudentEvents and SearchEvents requests

### ISSUE THREAD

**Issue by an2508374** [SaintAngeLs/p_software_engineering_2#106]
![Screenshot from 2024-04-30 01-38-13](https://github.com/SaintAngeLs/p_software_engineering_2/assets/148250180/1fc44a78-3465-4b60-93d7-73190c98f544)
![Screenshot from 2024-04-30 01-38-36](https://github.com/SaintAngeLs/p_software_engineering_2/assets/148250180/e6489f55-1126-4770-9d45-8f6f85cc4dc6)

**Comment by eggwhat** [comment]
Well, the search events and getting events for student only returns events with state Published and all events in db are already Archived. Maybe I should also make it possible to browse archived events? Or just allow archived and sort the results so that archived will be always last?

**Comment by an2508374** [comment]
Thanks for clarification, I think it would be nice if archived events were allowed to browse, then at frontend side we would have some checkbox to manage if someone want to see all events or only current ones. And then archived events should be always presented last.

**Comment by eggwhat** [comment]
Ok, so i will add state option to request body and by default it will get both published and archived events sorted accordingly (the many arguments sort seems to be working fine). Then if state field will not be empty it will give only events of given state (except toBePublished).

**Comment by eggwhat** [comment]
Should be working now

**Comment by an2508374** [comment]
It works nice, thank you @eggwhat!
