### ISSUE TITLE
Question about friends and getting all the students. 

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/p_software_engineering_2#108]
For the application specification the student should be able to invite other student in friend relations. In this case the GET: /students in the students service should be visible no only for the role of admin. Is this assumption has a chance for brief existence? Or there should be the other way of understanding the exact way students are invited? Please help me carving in this issue :O

**Comment by an2508374** [comment]
I think there will be no problem if getting all students becomes accessible not only for admin.

**Comment by SaintAngeLs** [comment]
> I think there will be no problem if getting all students becomes accessible not only for admin.

@an2508374 Thank you.
