### ISSUE TITLE
Issue with Organizations Service

### ISSUE THREAD

**Issue by an2508374** [SaintAngeLs/p_software_engineering_2#117]
I've observed a problem associated with external events: OrganizerRightsGranted and OrganizerRightsRevoked coming from Identity Service.  Organizations service seems to be unable to handle this messages.

After granting rights to organizer:
![1](https://github.com/SaintAngeLs/p_software_engineering_2/assets/148250180/1e8876fa-24c1-40e8-a514-9b2bbbc96452)

After revoking rights to organizer who granted rights before:
![2](https://github.com/SaintAngeLs/p_software_engineering_2/assets/148250180/d68e368e-49cb-4d68-b226-154fdd5f73e5)

**Comment by eggwhat** [comment]
It should be fixed in (#118). The handlers were properly adding and deleting organizers, but I didn't realize that mapper was throwing an exception. Thank you for letting me know.

**Comment by an2508374** [comment]
Thanks, unfortunately I've found one more issue.  Organizer can be added to organization many times and its removing from organization doesn't delete its ids from organizers property.

![1](https://github.com/SaintAngeLs/p_software_engineering_2/assets/148250180/e425b8b2-8828-4873-9c51-bda248478d22)

**Comment by an2508374** [comment]
Also there can be a question: If organizer has rights revoked, its id must be removed from all organizations or not?

**Comment by eggwhat** [comment]
Hopefully everything works now. I just got seasharped. Regarding your latest comment, now it removes them from all organizations, but for the same reason it was not working. Should be working now, but I can change this functionality if needed

**Comment by an2508374** [comment]
@eggwhat, thank you, now it works nice!
