### ISSUE TITLE
Question with rootOrganizationId during creating new event

### ISSUE THREAD

**Issue by an2508374** [SaintAngeLs/p_software_engineering_2#155]
There is a problem because GetOrganizerOrganizations query gives only IEnumerable<OrganizationDto> where we have Id and Name for each organization, meanwhile AddEvent command in Events Service requires RootOrganizationId to validate organization by GetOrganization query. So there some update is needed, I think there are two options here:

1. GetOrganizerOrganizations returns dtos with Id, Name and RootId.
2. GetOrganization not requires RootId and checks all documents in organizations collection.

I think the first option would be better, but may be more complicated in implementation. Which way should we go?

**Comment by eggwhat** [comment]
I added RootId field to make queries faster, but maybe it just makes everything more complicated. For now i will quickly go with first option
