### ISSUE TITLE
Test update

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/p_software_engineering_2#17]
@eggwhat, update the target framework in the tests project for the .net8.0 as the github has an previous versions unsupported.

**Comment by eggwhat** [comment]
I think it was taken care of in #13

**Comment by SaintAngeLs** [comment]
Yeap, you're correct, sorry for hustle-bustle :)

**Comment by SaintAngeLs** [comment]
After a thorough examination and mindful consideration, we've decided to close this issue due to prolonged inactivity, trusting that the essence of its intent will resurface in our future endeavors should the winds of collaboration breathe life into its sails once again.
