### ISSUE TITLE
Post.Service

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/p_software_engineering_2#32]
# Minispace.Services.Post

## Core

Core repository will contain the objects and dtos for the 'Students'  and the 'Post' databases of cluster.

### Post:
Post object: 
+ postId: guid

+ eventId: guid

+ author: <Student>

+ textContent: string

+ image/video?: string(binary)

+ method(): Type

### Studnet
- guid SudetntId
- string StudentFullName
- 
## Endpoints:
Endpoints for the evetns:
- POST: /post
- PUT: /post/{post_id}
- GET: /post/get
- DELETE: /post/{post_id}

## Content length
Maximum signs 5000

**Diagram**: https://app.diagrams.net/#G1BsP1sv_9fAmCtE4uVDHizcFcp7TqqvXc#%7B%22pageId%22%3A%229VrkRtQQe1OaMDu59Q1v%22%7D

**Comment by an2508374** [comment]
Due to the fact that we would like to have Posts Service working for frontend development in a relatively short time, I decided to take care of preparing it. @olegkiprik, in that situation you will be assigned to some other service. I think Reactions Service can be a great option for you to begin in a quite smooth way. What do you think?

**Comment by olegkiprik** [comment]
I'm sorry about my slow responsiveness. I agree with your suggestion.

**Comment by eggwhat** [comment]
Is this service working/finished? If so we should merge it with dev

**Comment by eggwhat** [comment]
- [ ] background worker for posts publish date

**Comment by eggwhat** [comment]
I provided necessary changes, but I think that now GetPosts request returns all posts regardless of their state. It shouldn't probably work like that, so what endpoints do we need for getting posts?

**Comment by eggwhat** [comment]
So far i added an endpoint for getting all posts for organizer. Do we want something more @an2508374 ?

**Comment by eggwhat** [comment]
Also right now state reported doesn't have any functionality and aren't in draft and hidden functionally the same state?

**Comment by an2508374** [comment]
> So far i added an endpoint for getting all posts for organizer. Do we want something more @an2508374 ?

Thank you @eggwhat, I think endpoints which we have now will be sufficient.

**Comment by an2508374** [comment]
> Also right now state reported doesn't have any functionality and aren't in draft and hidden functionally the same state?

State reported will be used if user reports a post and then only admin can republish or delete that post. And I agree that in draft and hidden are functionally the same state - in both a post is not visible for public and its content can be edited.

**Comment by eggwhat** [comment]
- [ ] endpoint for getting user posts for events that user signed up to
