### ISSUE TITLE
Deadline for Comments and Reactions Services

### ISSUE THREAD

**Issue by an2508374** [SaintAngeLs/p_software_engineering_2#56]
I would like to underline an essential fact that Comments Service and Reactions Service have to be done until next Monday - April 22nd.
- Firstly, we will show it to our supervisor (Mr Sulecki) during first pointed checkpoint so he could know that work in our team is approximately divided in an equal way. Please, pay attention to the fact that this will have an impact for our mark.
- Secondly, frontend is aimed to be developed very intensively on days and these services are needed next after Students, Events and Posts (which were done or are almost done).

@zniwiarzxxx, @olegkiprik, the whole Our team believes in You. Our project is in phase that we have beautiful plans, a great deal of work to do and a lack of working people. It's best time to go for work, thanks to it we will achieve our targets together!

**Comment by SaintAngeLs** [comment]
All the deadlines were not met. I do close this issue due do the lack of any farther activity.
